AWSTemplateFormatVersion: 2010-09-09

Parameters:
  S3BucketName:
    Type: String
    Default: photos-bucket-cf-vedanginew7

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    DependsOn: Lambda1InvokePermission
    Properties:
      BucketName: !Ref S3BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !GetAtt [ Lambda1, Arn]


  RestApiGatewayOfSmartPhotoAlbum:
    Type: AWS::ApiGateway::RestApi
    DeletionPolicy: Delete
    Properties:
      BinaryMediaTypes: ["*/*"]
      Name: "AI Photo Search CF 7"
      Description: "AI Photo Search application, built during the Cloud and Big Data course at Columbia University."
      Body:
        swagger: "2.0"
        info:
          description: "AI Photo Search application, built during the Cloud and Big Data course\
            \ at Columbia University."
          version: "1.0.0"
          title: "AI Photo Search"
        host: "l23l1p0qti.execute-api.us-east-1.amazonaws.com"
        basePath: "/v1"
        schemes:
        - "https"
        paths:
          /search:
            get:
              operationId: "searchPhotos"
              produces:
              - "application/json"
              parameters:
              - name: "q"
                in: "query"
                required: false
                type: "string"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/SearchResponse"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                "500":
                  description: "500 response"
                  schema:
                    $ref: "#/definitions/Error"
                "403":
                  description: "403 response"
                  schema:
                    $ref: "#/definitions/Error"
              x-amazon-apigateway-integration:
                httpMethod: "POST"
                uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:112295921782:function:search-photos-cf-7/invocations"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
          /upload/{folder}/{object}:
            put:
              parameters:
              - name: "object"
                in: "path"
                required: true
                type: "string"
              - name: "folder"
                in: "path"
                required: true
                type: "string"
              - name: "x-amz-meta-customLabels"
                in: "header"
                required: false
                type: "string"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
              x-amazon-apigateway-integration:
                credentials: "arn:aws:iam::112295921782:role/api-gateway-upload-to-s3"
                httpMethod: "PUT"
                uri: "arn:aws:apigateway:us-east-1:s3:path/{bucket}/{key}"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestParameters:
                  integration.request.header.x-amz-meta-customLabels: "method.request.header.x-amz-meta-customLabels"
                  integration.request.path.key: "method.request.path.object"
                  integration.request.path.bucket: "method.request.path.folder"
                passthroughBehavior: "when_no_match"
                type: "aws"
            options:
              consumes:
              - "application/json"
              parameters:
              - name: "folder"
                in: "path"
                required: true
                type: "string"
              - name: "object"
                in: "path"
                required: true
                type: "string"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'OPTIONS,PUT'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,x-amz-meta-customLabels,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
        definitions:
          Error:
            type: "object"
            properties:
              code:
                type: "integer"
                format: "int32"
              message:
                type: "string"
          Photo:
            type: "object"
            properties:
              url:
                type: "string"
              labels:
                type: "array"
                items:
                  type: "string"
          SearchResponse:
            type: "object"
            properties:
              results:
                type: "array"
                items:
                  $ref: "#/definitions/Photo"
        x-amazon-apigateway-gateway-responses:
          DEFAULT_4XX:
            responseParameters:
              gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
              gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          DEFAULT_5XX:
            responseParameters:
              gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
              gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        x-amazon-apigateway-binary-media-types:
        - "image/png"
        - "image/jpeg"
        - "image/jpg"

  ApiGatewayDeployment:
      Type: "AWS::ApiGateway::Deployment"
      Properties:
          RestApiId: !Ref RestApiGatewayOfSmartPhotoAlbum
    
  ApiGatewayStage:
      Type: "AWS::ApiGateway::Stage"
      Properties:
          StageName: "v1"
          DeploymentId: !Ref ApiGatewayDeployment
          RestApiId: !Ref RestApiGatewayOfSmartPhotoAlbum
          CacheClusterEnabled: false
          CacheClusterSize: "0.5"
          MethodSettings: 
            - 
              CacheDataEncrypted: false
              CacheTtlInSeconds: 300
              CachingEnabled: false
              DataTraceEnabled: false
              HttpMethod: "*"
              MetricsEnabled: false
              ResourcePath: "/*"
              ThrottlingBurstLimit: 5000
              ThrottlingRateLimit: 10000
          TracingEnabled: false

  ESInstance:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: photos-cf-7
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: True
        VolumeType: gp2
        VolumeSize: 10
      AccessPolicies: {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": "*"
              },
              "Action": [
                "es:*",
                "indices:data/write/bulk*",
                "indices:data/write/delete",
                "indices:data/write/index",
                "indices:data/write/update",
                "indices:data/rad/search"
              ],
              "Resource": "arn:aws:es:us-east-1:112295921782:domain/photos-cf-7/*"
              # # "Resource": "arn:aws:es:us-east-1:112295921782:domain/photos-cf/*"
              # "Resource" : "arn:aws:es:${self:provider.region}:${AWS::AccountId}:domain/photos-cf-7${self:provider.stage}/*"

            }
          ]
        }

  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument: 
        {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "PublicReadGetObject",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": "arn:aws:s3:::photos-bucket-cf-vedanginew7/*"
          },
          {
              "Sid": "ListObjectsInBucket",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:ListBucket",
              "Resource": "arn:aws:s3:::photos-bucket-cf-vedanginew7"
          },
          {
              "Sid": "AllObjectActions",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:*Object",
              "Resource": "arn:aws:s3:::photos-bucket-cf-vedanginew7/*"
          }
        ]
      }
      Bucket: !Ref AssetsBucket

  MyRoleLambdas1:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "lambda.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
      }
      ManagedPolicyArns: [
                "arn:aws:iam::aws:policy/AmazonS3FullAccess",
                "arn:aws:iam::aws:policy/AmazonRekognitionFullAccess",
                "arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess"
            ]
      Path: "/"
      Policies: 
        - PolicyName: "PolicyIp1"
          PolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": "logs:CreateLogGroup",
                  "Resource": "arn:aws:logs:us-east-1:112295921782:*"
              },
              {
                  "Effect": "Allow",
                  "Action": [
                      "logs:CreateLogStream",
                      "logs:PutLogEvents"
                  ],
                  "Resource": [
                      "arn:aws:logs:us-east-1:112295921782:log-group:/aws/lambda/index-photos-cf-7:*"
                  ]
              },
              {
                  "Effect": "Allow",
                  "Action": [
                      "logs:CreateLogStream",
                      "logs:PutLogEvents"
                  ],
                  "Resource": [
                      "arn:aws:logs:us-east-1:112295921782:log-group:/aws/lambda/index-photos-cf-7:*"
                  ]
              }
          ]
          }
      RoleName: index-photos-lambda-cf-7 
     
  MyRoleLambdas2:    
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "lambda.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
      }
      ManagedPolicyArns: [
                "arn:aws:iam::aws:policy/AmazonLexFullAccess",
                "arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess"
            ]
      Path: "/"
      Policies: 
        - PolicyName: "Splex1"
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
                {
                  "Sid": "VisualEditor0",
                  "Effect": "Allow",
                  "Action": [
                    "lex:CreateUploadUrl",
                    "lex:ListBuiltInSlotTypes",
                    "lex:ListBots",
                    "lex:ListBuiltInIntents",
                    "lex:ListImports",
                    "lex:ListExports"
                ],
                "Resource": "*"
              },
              {
                "Sid": "VisualEditor1",
                "Effect": "Allow",
                "Action": "lex:*",
                "Resource": [
                    "arn:aws:lex:us-east-1:112295921782:bot-alias/ZF3N9OLCQF/BRVKTMYOOF",
                    "arn:aws:lex:us-east-1:112295921782:bot/ZF3N9OLCQF"
                ]
              },
            ]
          }  
        - PolicyName: "SpDefault1"
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
                {
                  "Effect": "Allow",
                  "Action": "logs:CreateLogGroup",
                  "Resource": "arn:aws:logs:us-east-1:112295921782:*"
              },
              {
                "Effect": "Allow",
                "Action": [
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                ],
                "Resource": [
                  "arn:aws:logs:us-east-1:112295921782:log-group:/aws/lambda/search-photos-cf-7:*"
                ]
              },
              {
                "Effect": "Allow",
                "Action": [
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                ],
                "Resource": [
                  "arn:aws:logs:us-east-1:112295921782:log-group:/aws/lambda/search-photos-cf-7:*"
                ]
              }
            ]
          }     
      RoleName: search-photos-lambda-cf-7

  ClientBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: PublicWebsitePolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ClientBucket
                - /*
      Bucket: !Ref ClientBucket

  Lambda1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: myphotoalbumlambdas
        S3Key: deployment_package1.zip
      Description: Lambda function Index CF
      MemorySize: 128
      Environment:
        Variables:
          REGION: us-east-1
      Handler: lambda_function.lambda_handler
      Role: !GetAtt [MyRoleLambdas1, Arn]
      Timeout: 30
      Runtime: python3.9
      FunctionName: index-photos-cf-7

  Lambda2:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: myphotoalbumlambdas
        S3Key: deployment_package.zip
      Description: Lambda function Search CF    
      MemorySize: 128
      Environment:
        Variables:
          REGION: us-east-1
      Handler: lambda_function.lambda_handler
      Role: !GetAtt [MyRoleLambdas2, Arn]
      Timeout: 30
      Runtime: python3.9
      FunctionName: search-photos-cf-7

  Lambda1InvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: Lambda1
    Properties: 
      FunctionName:
        Fn::GetAtt:
          - Lambda1
          - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${S3BucketName}
  
  


Outputs:
  WebsiteURL:
    Value: !GetAtt
      - ClientBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - ClientBucket
          - DomainName
    Description: Name of S3 bucket to hold website content